### ISSUE TITLE
Print head losing position when print ends

### ISSUE THREAD

**Issue by ctday** [donovan6000/M33-Fio#188] opened 2016-10-01 17:10 UTC
My Raspberry Pi 3 running OctoPrinter and M33 Fio with iMe firmware, lastest versions all round, loses track of the printhead's position after a print ends, either naturally or on a Cancel. If I immediately start another print, it starts way out of position, usually far to the left and fairly randomly in Y. It seems to take at least a bed calibration or two for the system to figure out where it actually is. Any ideas?

**Comment by donovan6000** [comment] 2016-10-02 07:33
Is this being caused by the X/Y jerk homing being too sensitive? iMe's homing algorithm uses the accelerometer to detect when the extruder hits the back and right walls, and this detection can fail depending on the jerk sensitivity. Try setting the jerk sensitivities to something really low, like 1, in the M33 Fio tab of OctoPrint's settings to see if that's what's causing the problem.

**Comment by donovan6000** [comment] 2016-11-21 12:47
It's been awhile since anyone's responded to this issue, so I'll probably close it in a couple of days. Let me know if you still have any interest in fixing/testing this problem.

**Closed** 2016-11-24 03:12 UTC
